# Generated by Django 5.0.6 on 2025-02-06 20:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotifyapp', '0002_remove_song_user_song_users_alter_song_acousticness_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='acousticness',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='album_art',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='artist_names',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='song',
            name='danceability',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='energy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='genres',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='instrumentalness',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='liveness',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='popularity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='speechiness',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='users',
            field=models.ManyToManyField(related_name='songs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='song',
            name='valence',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
