# Generated by Django 5.0.6 on 2025-02-07 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotifyapp', '0003_alter_song_acousticness_alter_song_album_art_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='acousticness',
        ),
        migrations.RemoveField(
            model_name='song',
            name='danceability',
        ),
        migrations.RemoveField(
            model_name='song',
            name='energy',
        ),
        migrations.RemoveField(
            model_name='song',
            name='instrumentalness',
        ),
        migrations.RemoveField(
            model_name='song',
            name='liveness',
        ),
        migrations.RemoveField(
            model_name='song',
            name='speechiness',
        ),
        migrations.RemoveField(
            model_name='song',
            name='valence',
        ),
    ]
